---
title: "Workflow 12-12"
output: html_document
date: "2025-12-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
# Load required package
install.packages("openxlsx")
library(openxlsx)
library(here)

# Load the data

Q1_data <- read.xlsx(here("Q1_data.xlsx"))

# Inspect original values
table(Q1_data$Sex, useNA = "ifany")

# Clean Sex column 
Q1_data$Sex <- ifelse(
  Q1_data$Sex == "M" | Q1_data$Sex == "male" | Q1_data$Sex == "Male",
  "Male",
  ifelse(
    Q1_data$Sex == "F" | Q1_data$Sex == "female" | Q1_data$Sex == "Female",
    "Female",
    NA
  )
)

# Tabulate cleaned data
table(Q1_data$Sex, useNA = "ifany")
```
```{r}
setwd("/Users/simonahausleitner/Documents/Cambridge /ConRR/Data Sets")

# Tabulate Birth year by sex 
Q2_data <- read.xlsx("Q2_data.xlsx")
xtabs( ~ DOBYear + Sex, data = Q2_data)

```
```{r}
setwd("/Users/simonahausleitner/Documents/Cambridge /ConRR/Data Sets")

# Read in the data 
Q3_data <- read.xlsx("Q3_data.xlsx")

# Clean Sex column 
Q3_data$Sex <- ifelse(
  Q3_data$Sex == "M" | Q3_data$Sex == "male" | Q3_data$Sex == "Male",
  "Male",
  ifelse(
    Q3_data$Sex == "F" | Q3_data$Sex == "female" | Q3_data$Sex == "Female",
    "Female",
    NA
  )
)

# Tabulate 
xtabs( ~ DOBYear + Sex, data = Q3_data)
```

